name: praktikum8
description: Praktikum Notifikasi dan API Perangkat Keras - Kamera & Galeri
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
